spring:
  banner:
    location: baners/logo-dev.txt
    charset: UTF-8
  datasource:
    url: jdbc:postgresql://xxx:xxx/xxx
    username: xxx
    password: xxx
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
