server:
  port: 8080
spring:
  profiles:
    default: prod
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase/changelog.xml
    enabled: true
application:
  title: ${application.title}
  version: ${application.version}

