server:
  port: 8080
spring:
  profiles:
    default: prod
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  title: ${application.title}
  version: ${application.version}

