spring:
  banner:
    location: baners/logo-dev.txt
    charset: UTF-8
  datasource:
    url: jdbc:postgresql://xxx:xxx/xxx
    username: xxx
    password: xxx
  jpa:
    hibernate:
      ddl-auto: create
