server:
  port: 8080
spring:
  jpa:
    open-in-view: false
  profiles:
    default: prod
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    execute-in-transaction: true
application:
  title: ${application.title}
  version: ${application.version}

